USE burger_db;

insert into burgers (burger_name)
    values  
("New Bacon-ings (Comes with Bacon)"),
("The Child Molester (Comes with Candy!)"),
("Neva Been Feta Burger"),
("Foot Feta-ish Burger"),
("Tunami"),
("Mission A-Corn-Plished Burger (Comes with Corn Salsa)"),
("Pepper Don't Preach Burger"),
("Rest In Peas Burger"),
("Sexy Dance Fighting"),
("Fig-eta Bout It Burger"),
("Chevre Which Way But Loose Burger"),
("The Roquefort Files Burger"),
("These Collards Don't Run Burger"),
("Totally Radish Burger (Comes with Radish)"),
("Onion Burger - Grilled....To Death!"),
("Last of the Mo-Jicama Burger (Comes with Jicama)"),
("Olive And Let Die Burger"),
("Thank God It's Fried Egg Burger"),
("Camembert-ly Legal Burger"),
("Krauted House Burger"),
("Poblano Picasso Burger"),
("Salvador Cauliflower Burger"),
("Spaghetti Western and Meatballs"),
("Shoot out at the Okra Corral Burger"),
("Hit Me With Your Best Shallot Burger"),
("The Sound & The Curry Burger"),
("I've Created a Muenster Burger"),
("Something's NOT Fishy Burger (100% Beef)"),
("Neither Fish Nor Fowl Burger (100% Beef)"),
("One Fish, Two Fish, Red Fish Hamburger"),
("Take Me Out To The Burger (Comes with Peanuts and Crackerjacks)"),
("I'm Mad About Saffron (Made with No Saffron)"),
("Chard To A Crisp Burger"),
("Burger A La Mode - Comes with ice cream (Not on top)"),
("Shake Your Honeymaker Burger (Comes with Honey Mustard)"),
("Use It Or Bleus It Burger (Comes with Bleu Cheese)"),
("The One Yam Band Burger (Comes with Yams)"),
("Do Brussel Burger (Comes with Brussel Sprouts)"),
("Papaya Was A Rolling Stone Burger"),
("Good Night and Good Leek Burger"),
("Band On The Bun Burger (Comes with Wings)"),
("Chorizo Your Own Adventure Burger"),
("It's Fun To Eat At The rYeMCA Burger (Comes on Rye w/ Mustard, Cheese & Avocado)"),
("If Looks Coud Kale Burger"),
("Litter Swiss Bunshine Burger"),
("Girls Just Wanna Have Fennel Burger"),
("The Final Kraut Down Burger (Comes with Sauerkraut)"),
("Sit and Spinach Burger"),
("Sweaty Palms Burger (Comes with Hearts of Palm)"),
("Poutine on the Ritz Burger (Comes with Poutine Fries)"),
("Mesclun Around Burger"),
("The Don't Get Creme Fraiche With Me Burger"),
("Onion-tended Consequences Burger"),
("Bruschetta 'Bout It Burger"),
("MediterrAin't Misbehavin' Burger"),
("I'm Gonna Get You Succotash Burger"),
("Two Karat Burger (Comes with two Carrots)"),
("Say It Ain't Cilantro Burger (Doesn't come with cilantro. Because cilantro is terrible.)"),
("Not If I Can Kelp It Burger"),
("The Jack-O-Lentil Burger"),
("Itsy Bitsy Teeny Weenie Yellow Polka-Dot Zucchini Burger"),
("Summer Thyme Burger"),
("Butterface Burger (Served with Butter Lettuce)"),
("Beets Me Burger"),
("We're Here. We're Gruyere. Get Used to It. Burger"),
("Plymouth Roquefort Burger"),
("She's a Super Leek Burger (Comes with Braised Leeks)"),
("Let's Get Frisée Burger"),
("Open Sesame Burger (Served Open-faced on a Sesame Seed Bun)"),
("Chipotle Off the Old Block Burger"),
("Don't Give Me No Chive Burger (Served with no Chives)"),
("Pickle My Funny Bone Burger"),
("Yes I Cayenne Burger"),
("Bean Spirit - Come with Beans"),
("One Horse Open Slaw Burger (Comes with Slaw, no Horse)"),
("Santa Claus Is Cumin to Town Burger (With Cumin)"),
("Fifth Day of Christmas Burger (Comes with five Golden Rings of Onion)"),
("Jingle Bell Pepper Burger"),
("Home for the Challah-Days Burger (Comes on a Challah Roll)"),
("The Silentil Night Burger (Comes with Lentils)"),
("50 Ways to Leave Your Guava Burger"),
("Ruta-Bag-A Burger"),
("Don't Go Brocking My Heart Burger (With Broccoli and Artichoke Hearts)"),
("Eggers Can't Be Cheesers Burger (With Fried Egg and Cheese)"),
("Freedom of Choys Burger (Comes with Bok Choy)"),
("Grandpa Muenster Burger (10% Senior Discount)"),
("Mushroom With A View Burger (Porcini on a Double Decker)"),
("I Heartichoke You Burger"),
("Don't You Four Cheddar 'Bout Me Burger (Comes with four kinds of Cheddar)"),
("I Mint to Do Tha Burger (Comes with Mint Relish)"),
("Only the Provolonely Burger (Comes with Provolone)"),
("Sharp Cheddar Dressed Man (Comes with Sharp Cheddar)"),
("I Know Why the Cajun Burger Sings"),
("Tarragon in Sixty Seconds Burger"),
("Chile Relleno-You-Didn't Burger"),
("Top Bun Burger (Comes on our best Seven-grain Bun)"),
("So Many Fennel, So Little Thyme Burger (Comes with lots of Fennel, no Thyme)"),
("National Pass-Thyme Burger"),
("Free To Brie You and Me Burger"),
("Woulda Coulda Gouda"),
("You Gouda Be Kidding Me"),
("As Gouda As It Gets"),
("Gouda Gouda Gumdrops"),
("A Few Gouda Men"),
("Gouda Gouda Two Shoes (It comes with shoes)"),
("Gouda Day Sir"),
("The Cauliflower's Cumin from Inside the House Burger (Comes with Cauliflower)"),
("Sprouts! Sprouts! Sprouts It All Out! Burger"),
("A Leek of Their Own Burger"),
("Gourdon-Hamsey Burger - (Comes with Squash and Ham)"),
("I'm OK, You're Ok-ra Burger"),
("Bohemian Radishy Burger"),
("Edward James Olive-most Burger"),
("Is This Your Chard Burger"),
("Caper Magic To Yourself Burger"),
("I Don't Bay Leaf in Magic Burger"),
("Winter Muensterland Burger with Muenster cheese (Side of Snow Peas)"),
("The Longest Chard Burger"),
("Kale Mary Burger (Served with Kale)"),
("The Troy Oinkman Burger (Served with Bacon)"),
("It's Only Sourdough Burger (But I Like It)"),
("Enoki Dokie Burger (Comes with Enoki Mushrooms)"),
("I Fought the Slaw Burger (And the Slaw Won)"),
("Charbroil Fair Burger (Comes with Parsley, Sage, Rosemary, and Thyme)"),
("Beets of the Southern Wild Burger"),
("Sympathy for the Deviled Egg Burger"),
("The Life of the Parsley Burger"),
("Sweet Home Avocado Burger"),
("To Err Is Cumin Burger"),
("Onion Ring Around the Rosemary Burger"),
("Parma Parma Parma Chameleon Burger (With Parmesan crisp)"),
("Bleu by You Burger (With locally sourced Bleu Cheese)"),
("The Saffron, Saff-off Burger"),
("Texas Chainsaw Massa-curd Burger"),
("The Human Polenta-pede Burger"),
("Kales From the Crypt Burger"),
("Paranormal Pepper Jack-tivity Burger"),
("Sub-conscious Burger (On a Sub Roll)"),
("Romaines of the Day Burger"),
("Pasnips-Vous Francais Burger"),
("Beet-er Late Than Never"),
("Peas and THank You Burger"),
("Bes Burger"),
("Run Gorgonzola Run Burger (Made with Gorgonzola)"),
("Cheeses is Born Burger"),
("Cajun Gracefully Burger"),
("Blondes Have More Fun-gus Burger (Comes with Mushrooms)"),
("Beets of Burden Burger"),
("Blue is the Warmest Cheese Burger"),
("Three Beets to the Wind Burger"),
("The Grand Brie Burger"),
("A Good Manchego is Hard to Find Burger"),
("The Garden of Eden Burger (Served with Apple)"),
("The Garden of E-dumb Burger (Served with Crapple)"),
("Shoestring Around the Rosey Burger"),
("Let It Snow Peas Burger"),
("The Millie-churian Candidate"),
("Knife to ... You Burger (With THinkly Sliced Bun)"),
("I Ran, So Tar... Burger"),
("Curd-fect Strangers Burger (Comes with Cheese Curds)"),
("Sweet Chili O' Mine Burger"),
("The Six Scallion Dollar Man Burger"),
("Let's Give 'em something Shiitake 'bout Burger"),
("If You've Got It, Croissant It Burger"),
("Chile Relleno-You-Didn't Burger"),
("Parm-pit Burger"),
("Scent of a Cumin Burger"),
("She'll Be Coming 'Round the Plantain Burger"),
("Take A Leek Burger (Comes with Sautéed Lettuce)"),
("Who Wants To Be A Scallionaire Burger?");

SELECT * FROM burgers;