USE burger_db;

insert into burgers (burger_name)
    values  
("New Bacon-ings (Comes with Bacon)"),
("The Child Molester (Comes with Candy!)"),
("Crawl Space"),
("Neva Been Feta Burger"),
("Foot Feta-ish Burger"),
("Tunami"),
("Sacred Cow"),
("Mission A-Corn-Plished Burger (Comes with Corn Salsa)"),
("Pepper Don't Preach Burger"),
("Rest In Peas Burger"),
("Sexy Dance Fighting"),
("Fig-eta Bout It Burger"),
("Chevre Which Way But Loose Burger"),
("The Roquefort Files Burger"),
("These Collards Don't Run Burger"),
("Hamburger Dinner Theatre"),
("Totally Radish Burger (Comes with Radish)"),
("Onion Burger - Grilled....To Death!"),
("Last of the Mo-Jicama Burger (Comes with Jicama)"),
("Sheesh! Cab, Bob?"),
("Olive And Let Die Burger"),
("Thank God It's Fried Egg Burger"),
("Bed & Breakfast"),
("Camembert-ly Legal Burger"),
("Krauted House Burger"),
("Art Crawl"),
("Poblano Picasso Burger"),
("Salvador Cauliflower Burger"),
("Spaghetti Western and Meatballs"),
("Shoot out at the Okra Corral Burger"),
("Burger Wars"),
("Hit Me With Your Best Shallot Burger"),
("The Sound & The Curry Burger"),
("Weekend at Mort's"),
("I've Created a Muenster Burger"),
("Lobsterfest"),
("Something's NOT Fishy Burger (100% Beef)"),
("Neither Fish Nor Fowl Burger (100% Beef)"),
("One Fish, Two Fish, Red Fish Hamburger"),
("Torpedo"),
("Take Me Out To The Burger (Comes with Peanuts and Crackerjacks)"),
("The Belchies"),
("I'm Mad About Saffron (Made with No Saffron)"),
("Bob Day Afternoon"),
("Chard To A Crisp Burger"),
("Synchronized Swimming"),
("Burger A La Mode - Comes with ice cream (Not on top)"),
("Shake Your Honeymaker Burger (Comes with Honey Mustard)"),
("Use It Or Bleus It Burger (Comes with Bleu Cheese)"),
("The One Yam Band Burger (Comes with Yams)"),
("Do Brussel Burger (Comes with Brussel Sprouts)"),
("Burgerboss"),
("Papaya Was A Rolling Stone Burger"),
("Good Night and Good Leek Burger"),
("Band On The Bun Burger (Comes with Wings)"),
("Food Truckin'"),
("Chorizo Your Own Adventure Burger"),
("Dr. Yap"),
("It's Fun To Eat At The rYeMCA Burger (Comes on Rye w/ Mustard, Cheese & Avocado)"),
("Moody Foodie"),
("If Looks Coud Kale Burger"),
("Litter Swiss Bunshine Burger"),
("Girls Just Wanna Have Fennel Burger"),
("The Final Kraut Down Burger (Comes with Sauerkraut)"),
("Bad Tina"),
("Sit and Spinach Burger"),
("Sweaty Palms Burger (Comes with Hearts of Palm)"),
("Beefsquatch"),
("Poutine on the Ritz Burger (Comes with Poutine Fries)"),
("Mesclun Around Burger"),
("The Don't Get Creme Fraiche With Me Burger"),
("Onion-tended Consequences Burger"),
("Bruschetta 'Bout It Burger"),
("MediterrAin't Misbehavin' Burger"),
("I'm Gonna Get You Succotash Burger"),
("Ear-sy Rider"),
("Two Karat Burger (Comes with two Carrots)"),
("Say It Ain't Cilantro Burger (Doesn't come with cilantro. Because cilantro is terrible.)"),
("Not If I Can Kelp It Burger"),
("Full Bars"),
("The Jack-O-Lentil Burger"),
("Bob Fires The Kids"),
("Itsy Bitsy Teeny Weenie Yellow Polka-Dot Zucchini Burger"),
("Summer Thyme Burger"),
("Butterface Burger (Served with Butter Lettuce)"),
("Beets Me Burger"),
("We're Here. We're Gruyere. Get Used to It. Burger"),
("An Indecent Thanksgiving Proposal"),
("Plymouth Roquefort Burger"),
("The Deepending"),
("She's a Super Leek Burger (Comes with Braised Leeks)"),
("Let's Get Frisée Burger"),
("Tina-rannosaurus Wrecks"),
("Open Sesame Burger (Served Open-faced on a Sesame Seed Bun)"),
("Chipotle Off the Old Block Burger"),
("Don't Give Me No Chive Burger (Served with no Chives)"),
("Pickle My Funny Bone Burger"),
("The Unbearable Like-Likeness of Gene"),
("Yes I Cayenne Burger"),
("Bean Spirit - Come with Beans"),
("God Rest Ye Merry Gentle-Mannequins"),
("One Horse Open Slaw Burger (Comes with Slaw, no Horse)"),
("Santa Claus Is Cumin to Town Burger (With Cumin)"),
("Fifth Day of Christmas Burger (Comes with five Golden Rings of Onion)"),
("Jingle Bell Pepper Burger"),
("Home for the Challah-Days Burger (Comes on a Challah Roll)"),
("The Silentil Night Burger (Comes with Lentils)"),
("Mother Daughter Laser Razor"),
("50 Ways to Leave Your Guava Burger"),
("Ruta-Bag-A Burger"),
("Nude Beach"),
("Don't Go Brocking My Heart Burger (With Broccoli and Artichoke Hearts)"),
("Eggers Can't Be Cheesers Burger (With Fried Egg and Cheese)"),
("Freedom of Choys Burger (Comes with Bok Choy)"),
("Broadcast Wagstaff School News"),
("Grandpa Muenster Burger (10% Senior Discount)"),
("Mushroom With A View Burger (Porcini on a Double Decker)"),
("My Fuzzy Valentine"),
("I Heartichoke You Burger"),
("Lindapendent Woman"),
("Don't You Four Cheddar 'Bout Me Burger (Comes with four kinds of Cheddar)"),
("I Mint to Do Tha Burger (Comes with Mint Relish)"),
("Only the Provolonely Burger (Comes with Provolone)"),
("O.T.: The Outside Toilet"),
("Sharp Cheddar Dressed Man (Comes with Sharp Cheddar)"),
("Topsy"),
("I Know Why the Caju Burger Sings"),
("Tarragon in Sixty Seconds Burger"),
("Two for Tina"),
("Chile Relleno-You-Didn't Burger"),
("The Kids Run the Restaurant"),
("Top Bun Burger (Comes on our best Seven-grain Bun)"),
("Top Butt Burger (Your face looks like a butt)"),
("Carpe Museum"),
("So Many Fennel, So Little Thyme Burger (Comes with lots of Fennel, no Thyme)"),
("The Unnatural"),
("National Pass-Thyme Burger"),
("Free To Brie You and Me Burger"),
("Woulda Coulda Gouda"),
("You Gouda Be Kidding Me"),
("As Gouda As It Gets"),
("Gouda Gouda Gumdrops"),
("A Few Gouda Men"),
("Gouda Gouda Two Shoes (It comes with shoes)"),
("Gouda Day Sir"),
("Fort Night"),
("The Cauliflower's Cumin from Inside the House Burger (Comes with Cauliflower)"),
("Seaplane!"),
("Sprouts! Sprouts! Sprouts It All Out! Burger"),
("My Big Fat Greek Bob"),
("A Leek of Their Own Burger"),
("Turkey in a Can"),
("Gourdon-Hamsey Burger - (Comes with Squash and Ham)"),
("Bob and Deliver"),
("I'm OK, You're Ok-ra Burger"),
("Bohemian Radishy Burger"),
("Edward James Olive-most Burger"),
("Presto Tina-o"),
("Is This Your Chard Burger"),
("Caper Magic To Yourself Burger"),
("I Don't Bay Leaf in Magic Burger"),
("Easy Com-mercial, Easy Go-mercial"),
("Winter Muensterland Burger with Muenster cheese (Side of Snow Peas)"),
("The Longest Chard Burger"),
("Kale Mary Burger (Served with Kale)"),
("The Troy Oinkman Burger (Served with Bacon)"),
("Uncle Teddy"),
("It's Only Sourdough Burger (But I Like It)"),
("The Kids Rob A Train"),
("Enoki Dokie Burger (Comes with Enoki Mushrooms)"),
("I Get Psy-chic Out of You"),
("I Fought the Slaw Burger (And the Slaw Won)"),
("Charbroil Fair Burger (Comes with Parsley, Sage, Rosemary, and Thyme)"),
("Beets of the Southern Wild Burger"),
("Sympathy for the Deviled Egg Burger"),
("The Equestranauts"),
("The Life of the Parsley Burger"),
("Ambergris"),
("Sweet Home Avocado Burger"),
("To Err Is Cumin Burger"),
("The Kids Run Away"),
("Onion Ring Around the Rosemary Burger"),
("Gene It On"),
("Parma Parma Parma Chameleon Burger (With Parmesan crisp)"),
("Bleu by You Burger (With locally sourced Bleu Cheese)"),
("How Bob Saves/Destroys the Town"),
("The Saffron, Saff-off Burger"),
("Tina and the Real Ghost"),
("Texas Chainsaw Massa-curd Burger"),
("The Human Polenta-pede Burger"),
("Kales From the Crypt Burger"),
("Paranormal Pepper Jack-tivity Burger"),
("Friends Wit Burger-Fits"),
("Sub-conscious Burger (On a Sub Roll)"),
("Romaines of the Day Burger"),
("Pasnips-Vous Francais Burger"),
("Beet-er Late Than Never"),
("Peas and THank You Burger"),
("Bes Burger"),
("Run Gorgonzola Run Burger (Made with Gorgonzola)"),
("Father of the Bob"),
("Cheeses is Born Burger"),
("Tina Tailor Soldier Spy"),
("Cajun Gracefully Burger"),
("Blondes Have More Fun-gus Burger (Comes with Mushrooms)"),
("Midday Run"),
("Beets of Burden Burger"),
("Speakeasy Rider"),
("Blue is the Warmest Cheese Burger"),
("Three Beets to the Wind Burger"),
("The Grand Brie Burger"),
("Late Afternoon in the Garden of Bob and Louise"),
("A Good Manchego is Hard to Find Burger"),
("The Garden of Eden Burger (Served with Apple)"),
("The Garden of E-dumb Burger (Served with Crapple)"),
("Shoestring Around the Rosey Burger"),
("Can't Buy Me Math"),
("Let It Snow Peas Burger"),
("The Millie-churian Candidate"),
("Knife to ... You Burger (With THinkly Sliced Bun)"),
("I Ran, So Tar... Burger"),
("The Gayle Tales"),
("Curd-fect Strangers Burger (Comes with Cheese Curds)"),
("L'il Hard Dad"),
("Sweet Chili O' Mine Burger"),
("Adventure In Chinchilla-sitting"),
("The Six Scallion Dollar Man Burger"),
("The Runway Club"),
("Let's Give 'em something Shiitake 'bout Burger"),
("Itty Bitty Ditty Committee"),
("If You've Got It, Croissant It Burger"),
("Chile Relleno-You-Didn't Burger"),
("Parm-pit Burger"),
("Scent of a Cumin Burger"),
("Housetrap"),
("She'll Be Coming 'Round the Plantain Burger"),
("Hawk & Chick"),
("Take A Leek Burger (Comes with Sautéed Lettuce)"),
("The Oeder Games"),
("Who Wants To Be A Scallionaire Burger?");

SELECT * FROM burgers;